name: Desplegar Angular en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build -- --configuration production

      - name: Configurar Git para despliegue
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github.com/daviddlv007/modelo_frontend_web.git
          git remote set-url --push origin https://$GH_TOKEN@github.com/daviddlv007/modelo_frontend_web.git

      - name: Desplegar en GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/frontend/browser
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
