name: Desplegar Angular en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto Angular
        run: npm run build -- --configuration production

      - name: Preparar archivos para GitHub Pages
        run: cp ./dist/frontend/browser/index.html ./dist/frontend/browser/404.html

      - name: Desplegar en GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/frontend/browser
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}